Fix issue for 2D model-space verification plots with zero difference (#585)
TYPE: bug fix

DESCRIPTION OF CHANGES:
When plotting a zero field on 2D, the subroutine plotTimeserial2D inside
basic_plot_functions.py fails, because the command
matplotlib.colors.TwoSlopeNorm(vmin=valuemin, vcenter=0, vmax=valuemax) gives the following
error: raise ValueError('vmin, vcenter, and vmax must be in ' ValueError: vmin, vcenter, and
vmax must be in ascending order

Now:
The vmin, vcenter, vmax are numerically distinguished by introducing epsilon=1.e-8 as
machine precision. The three variables are properly ordered for fields within machine
precision. This error disappears.

LIST OF MODIFIED FILES:
M graphics/basic_plot_functions.py

TESTS CONDUCTED: Allow 2D plots with zero difference for weekly cycling tests.